configurations:
  # support one of "bing", "google", "duckduckgo", need to configure API key below if using Bing or Google
  api_provider: duckduckgo
  result_count: 3 # number of result, should be a small number less then 10

  # Bing Web Search API
  # https://www.microsoft.com/en-us/bing/apis/bing-web-search-api
  #
  # register search resource on Azure Portal: https://aka.ms/bingapisignup
  # get api key from the registered resource
  bing_api_key:

  # Google Custom Search
  # https://developers.google.com/custom-search/v1/overview
  #
  # get search engine id from: https://cse.google.com/all
  # get search api key from: https://console.cloud.google.com/apis/credentials
  google_search_engine_id:
  google_api_key: